<?php 
# This file was automatically generated by the MediaWiki 1.17.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## General Settings
#$wgShowExceptionDetails = true;
$wgSitename      = 'MediaWiki for Sae';

## Paths
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = '';
$wgScriptExtension  = '.php';
$wgArticlePath      = '/$1';
$wgStylePath        = $wgScriptPath.'/skins';
$wgLogo             = $wgStylePath.'/common/images/wiki.png';

## Global Objects

## Email settings
$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO
$wgEmergencyContact = '';//Email帐号：需要用户自行设置 username@sina.com.cn
$wgPasswordSender   = '';//Email帐号：需要用户自行设置 username@sina.com.cn
$wgEnotifUserTalk      = true; # UPO
$wgEnotifWatchlist     = true; # UPO
$wgEmailAuthentication = true;
# 以下需要用户自行设置
$wgSMTP	= array(
 'smtp'     => 'smtp.qq.com',//请自行设置其他
 'port'     => '25',
 'tls'      => 'false',
 'username' => '',//Email帐号：需要用户自行设置 username@sina.com.cn
 'password' => '' //Email密码：需要用户自行设置 password
);
## Email notification (Enotif) settings

## Database settings
$wgDBtype           = 'mysql';
$wgDBserver         = SAE_MYSQL_HOST_M.':'.SAE_MYSQL_PORT;
$wgDBname           = SAE_MYSQL_DB;
$wgDBuser           = SAE_MYSQL_USER;
$wgDBpassword       = SAE_MYSQL_PASS;
$wgDBprefix         = 'wiki_';
$wgDBTableOptions   = 'ENGINE=MyISAM, DEFAULT CHARSET=binary';
## LoadBalancer settings
$wgDBservers = array(
     array(
         'host'     => SAE_MYSQL_HOST_M.':'.SAE_MYSQL_PORT,
         'dbname'   => SAE_MYSQL_DB,
         'user'     => SAE_MYSQL_USER,
         'password' => SAE_MYSQL_PASS,
         'type'     => $wgDBtype,
         'flags'    => DBO_DEFAULT,
         'load'     => 0,
     ),
     array(
         'host'     => SAE_MYSQL_HOST_S.':'.SAE_MYSQL_PORT,
         'dbname'   => SAE_MYSQL_DB,
         'user'     => SAE_MYSQL_USER,
         'password' => SAE_MYSQL_PASS,
         'type'     => $wgDBtype,
         'flags'    => DBO_DEFAULT,
         'load'     => 1,
     )
);
$wgMasterWaitTimeout = 10;					# How long to wait for a slave to catch up to the master
## MySQL specific
$wgDBmysql5 = false;
## Shared DB settings
## Compressed Storage Support

## Localization
$wgLanguageCode = 'zh-cn';				# Site language code, should be one of ./languages/Language(.*).php
$wgExtraLanguageNames = array();

## Cache
$wgMainCacheType    = CACHE_MEMCACHED;
## Memcached settings
$wgMemCachedServers = array( '' );

## Uploads
define('SAESTOR_DOMAIN',    'mediawiki');
define('SAESTOR_DOMAIN_DIR','');
$wgEnableUploads  			= true;
$wgFileExtensions 			= array( 'png', 'gif', 'jpg', 'jpeg' );
$wgUploadPath       		= $wgScriptPath.'/images';
$wgUploadDirectory	        = 'saestor://'.SAESTOR_DOMAIN.$wgScriptPath.'/images';
$wgUploadBaseUrl    		= 'http://'.$_SERVER['HTTP_APPNAME'].'-'.SAESTOR_DOMAIN.'.stor.sinaapp.com'.SAESTOR_DOMAIN_DIR;
$wgDeletedDirectory			= $wgUploadDirectory.'/deleted';
$wgHashedUploadDirectory	= true;		# divide your images directory into many subdirectories, for improved performance
$wgThumbnailScriptPath  	= false;
$wgGenerateThumbnailOnParse = true;
# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## Parser
## Tex
$wgUseTeX           = false;

## Proxies
$wgSecretKey = md5(SAE_SECRETKEY.'wgSecretKey').md5(SAE_ACCESSKEY.'wgSecretKey');	// 64位
$wgUpgradeKey = substr(md5(SAE_ACCESSKEY.'wgUpgradeKey'),8,16);						// 16位

## Skins
$wgDefaultSkin = "vector";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Access		# 默认只有注册用户才能编辑 
$wgGroupPermissions['*']['edit'] = false;		# The following permissions were set based on your choice in the installer

## Site customization
$wgResourceLoaderMaxQueryLength = -1;			# Query string length limit for ResourceLoader. 

# End of automatically generated settings.
# Add more configuration options below.

## Other settings
$wgShellLocale = 'en_US.utf8';
#$wgLocaltimezone = 'GMT';
#$wgLocalTZoffset = 'Asia/Shanghai';

$wgFooterIcons = array(
	'copyright' => array(
		'copyright' => array(
			//'src' => 'http://i.creativecommons.org/l/by/3.0/88x31.png',
			//'url' => 'http://creativecommons.org/licenses/by/3.0/',
			//'alt' => 'Attribution 3.0 Unported',
		), // placeholder for the built in copyright icon
	),
	'poweredby' => array(
		'sae' => array(
			'src' => 'http://static.sae.sina.com.cn/image/poweredby/poweredby.png',
			'url' => 'http://sae.sina.com.cn/',
			'alt' => 'Powered by Sina App Engine',
		),
		"mediawiki" => array(
			'src' => $wgStylePath.'/common/images/poweredby_mediawiki_88x31.png',
			'url' => 'http://www.mediawiki.org/',
			'alt' => 'Powered by MediaWiki',
		)
	),
);